stages:
  - test
  - release

lint:
  stage: test
  image: registry.gitlab.com/etke.cc/base
  script:
    - make lint

unit:
  stage: test
  image: registry.gitlab.com/etke.cc/base
  script:
    - make test

release:
  stage: release
  only: ['tags']
  image:
    name: goreleaser/goreleaser
    entrypoint: ['']
  script:
    - goreleaser release --rm-dist
