project_name: emm
before:
  hooks:
  - go mod tidy

builds:
  - main: ./cmd
    env:
      - CGO_ENABLED=0
    ldflags:
      - -extldflags "-static"
    flags:
      - -tags=timetzdata,goolm
    binary: emm
    goos:
      - freebsd
      - linux
      - darwin
    goarch:
      - arm64
      - amd64

nfpms:
  - vendor: https://etke.cc
    package_name: export-matrix-messages
    maintainer: etke.cc
    description: A CLI tool that joins the room and exports last N messages to the file you specified.
    homepage: https://gitlab.com/etke.cc/tools/emm
    license: GPL-3.0
    formats:
      - deb
      - rpm
      - apk
    file_name_template: "{{ .PackageName }}-{{ .Version }}_{{ .Os }}-{{ .Arch }}"

changelog:
  sort: asc
checksum:
  disable: true
archives:
  - format: binary
